apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-ha
  namespace: access-control
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:16

  affinity:
    enablePodAntiAffinity: true
    podAntiAffinityType: required
    topologyKey: kubernetes.io/hostname

  probes:
    startup:
      initialDelaySeconds: 10
      periodSeconds: 5
      failureThreshold: 15

  bootstrap:
    initdb:
      database: portaria
      owner: portaria_user
      secret:
        name: portaria-db-credentials

  storage:
    size: 5Gi
    storageClass: longhorn
